name: github-actions
on:
  push:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    env:
      PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
      PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
      PSQL_DATABASE: ${{ secrets.PSQL_DATABASE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.6.1"

      - name: Install node dependencies
        run: npm install

      - name: Setup POSTGRESQL
        run: |
          sudo service postgresql start
          echo "PSQL_DATABASE: ${{ secrets.PSQL_DATABASE }}"
          echo "PGPASSWORD=${{ secrets.DB_PASSWORD }}"
          sudo -u postgres psql -c "CREATE DATABASE PSQL_DATABASE;"

      - name: Try to Connect to PostgreSQL
        run: |
          psql -d "${{ secrets.PSQL_DATABASE }}" -U "${{ secrets.PSQL_USERNAME }}" -c 'SELECT 1;'

      - name: Run integration test cases
        run: npm run test
