name: integration-github-actions
on:
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    env:
      PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
      PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
      PSQL_DATABASE: ${{ secrets.PSQL_DATABASE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.6.1"

      - name: Install node dependencies
        run: npm install

      - name: Setup POSTGRESQL
        run: |
          sudo systemctl start postgresql.service
          echo "PSQL_DATABASE: ${{ secrets.PSQL_DATABASE }}"

      - name: Update PostgreSQL User Password
        run: |
          sudo -u postgres psql -c "CREATE USER ${{ secrets.PSQL_USERNAME }} WITH PASSWORD '${{ secrets.PSQL_PASSWORD }}';"
          sudo -u postgres psql -c "ALTER USER ${{ secrets.PSQL_USERNAME }} PASSWORD '${{ secrets.PSQL_PASSWORD }}';"
          sudo chown -R runner /var/log/webapp

      - name: Create database
        run: sudo -u postgres psql -c "CREATE DATABASE ${{secrets.PSQL_DATABASE}};"

      - name: Run integration test cases
        run: npm run integration-test
