name: packer-actions-validate
on:
  pull_request:

env:
  PSQL_USERNAME: "${{secrets.PSQL_USERNAME}}"
  PSQL_PASSWORD: "${{secrets.PSQL_PASSWORD}}"
  PSQL_DATABASE: "${{secrets.PSQL_DATABASE}}"

jobs:
  packer-validate:
    runs-on: ubuntu-latest
    env:
      PSQL_USERNAME: "${{secrets.PSQL_USERNAME}}"
      PSQL_PASSWORD: "${{secrets.PSQL_PASSWORD}}"
      PSQL_DATABASE: "${{secrets.PSQL_DATABASE}}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy to repository after zip
        run: cd .. && zip -r webapp.zip webapp && cp webapp.zip webapp/scripts/webapp.zip && cd webapp

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"

      - name: Run `packer init`
        id: init
        run: "packer init ./gcp.pkr.hcl"

      - name: Run `packer fmt`
        id: fmt
        run: packer fmt -check -diff ./gcp.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./gcp.pkr.hcl"
